# Repository → Settings → Pages 
# Source = GitHub Actions
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax

name: Deploy Dokka Docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - processing-library-example

# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
permissions:
  contents: read
  pages: write
  # GITHUB_TOKEN for actions/deploy-pages
  # https://docs.github.com/en/actions/concepts/security/openid-connect
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

        # Download repository
        # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v7

        # Install Java
        # https://github.com/actions/setup-java
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

        # Setup Gradle
        # https://github.com/gradle/actions/tree/main/setup-gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '9.5'

      - name: Generate Dokka
        run: gradle dokkaGenerate

        # Upload to GitHub pages
        # https://github.com/actions/upload-pages-artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: build/dokka/html
        # https://github.com/actions/deploy-pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
    
